In [1]:
import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv("Fish.csv")

df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [3]:
df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [6]:
le = LabelEncoder()

df["Species"] = le.fit_transform(df["Species"])

In [7]:
X = df.drop("Weight", axis=1)
y = df["Weight"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
svr = SVR(
    kernel="rbf",
    C=100,
    gamma=0.1,
    epsilon=0.1
)

svr.fit(X_train, y_train)

SVR(C=100, gamma=0.1)

In [11]:
y_pred = svr.predict(X_test)

In [12]:
print("Training Score :", svr.score(X_train, y_train))
print("Testing Score :", svr.score(X_test, y_test))

print("R² Score :", r2_score(y_test, y_pred))

Training Score : 0.8871346255359576
Testing Score : 0.9337492371253356
R² Score : 0.9337492371253356

In [13]:
pickle.dump(svr, open("model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))